/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandSlugRouteImport } from './routes/brand.$slug'
import { Route as BrandModelRouteImport } from './routes/$brand.$model'
import { Route as BrandSlugModelModelRouteImport } from './routes/brand.$slug.model.$model'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugRoute = BrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandModelRoute = BrandModelRouteImport.update({
  id: '/$brand/$model',
  path: '/$brand/$model',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugModelModelRoute = BrandSlugModelModelRouteImport.update({
  id: '/model/$model',
  path: '/model/$model',
  getParentRoute: () => BrandSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/maintenance': typeof MaintenanceRoute
  '/profile': typeof ProfileRoute
  '/$brand/$model': typeof BrandModelRoute
  '/brand/$slug': typeof BrandSlugRouteWithChildren
  '/brand/$slug/model/$model': typeof BrandSlugModelModelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/maintenance': typeof MaintenanceRoute
  '/profile': typeof ProfileRoute
  '/$brand/$model': typeof BrandModelRoute
  '/brand/$slug': typeof BrandSlugRouteWithChildren
  '/brand/$slug/model/$model': typeof BrandSlugModelModelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/maintenance': typeof MaintenanceRoute
  '/profile': typeof ProfileRoute
  '/$brand/$model': typeof BrandModelRoute
  '/brand/$slug': typeof BrandSlugRouteWithChildren
  '/brand/$slug/model/$model': typeof BrandSlugModelModelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands'
    | '/maintenance'
    | '/profile'
    | '/$brand/$model'
    | '/brand/$slug'
    | '/brand/$slug/model/$model'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brands'
    | '/maintenance'
    | '/profile'
    | '/$brand/$model'
    | '/brand/$slug'
    | '/brand/$slug/model/$model'
  id:
    | '__root__'
    | '/'
    | '/brands'
    | '/maintenance'
    | '/profile'
    | '/$brand/$model'
    | '/brand/$slug'
    | '/brand/$slug/model/$model'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsRoute: typeof BrandsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ProfileRoute: typeof ProfileRoute
  BrandModelRoute: typeof BrandModelRoute
  BrandSlugRoute: typeof BrandSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$slug': {
      id: '/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/brand/$slug'
      preLoaderRoute: typeof BrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$brand/$model': {
      id: '/$brand/$model'
      path: '/$brand/$model'
      fullPath: '/$brand/$model'
      preLoaderRoute: typeof BrandModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$slug/model/$model': {
      id: '/brand/$slug/model/$model'
      path: '/model/$model'
      fullPath: '/brand/$slug/model/$model'
      preLoaderRoute: typeof BrandSlugModelModelRouteImport
      parentRoute: typeof BrandSlugRoute
    }
  }
}

interface BrandSlugRouteChildren {
  BrandSlugModelModelRoute: typeof BrandSlugModelModelRoute
}

const BrandSlugRouteChildren: BrandSlugRouteChildren = {
  BrandSlugModelModelRoute: BrandSlugModelModelRoute,
}

const BrandSlugRouteWithChildren = BrandSlugRoute._addFileChildren(
  BrandSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsRoute: BrandsRoute,
  MaintenanceRoute: MaintenanceRoute,
  ProfileRoute: ProfileRoute,
  BrandModelRoute: BrandModelRoute,
  BrandSlugRoute: BrandSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
