/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandSlugRouteImport } from './routes/brand.$slug'
import { Route as BrandSlugModelRouteImport } from './routes/brand.$slug.$model'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugRoute = BrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugModelRoute = BrandSlugModelRouteImport.update({
  id: '/$model',
  path: '/$model',
  getParentRoute: () => BrandSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand/$slug': typeof BrandSlugRouteWithChildren
  '/brand/$slug/$model': typeof BrandSlugModelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand/$slug': typeof BrandSlugRouteWithChildren
  '/brand/$slug/$model': typeof BrandSlugModelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand/$slug': typeof BrandSlugRouteWithChildren
  '/brand/$slug/$model': typeof BrandSlugModelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/brand/$slug' | '/brand/$slug/$model'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brand/$slug' | '/brand/$slug/$model'
  id: '__root__' | '/' | '/brand/$slug' | '/brand/$slug/$model'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandSlugRoute: typeof BrandSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$slug': {
      id: '/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/brand/$slug'
      preLoaderRoute: typeof BrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$slug/$model': {
      id: '/brand/$slug/$model'
      path: '/$model'
      fullPath: '/brand/$slug/$model'
      preLoaderRoute: typeof BrandSlugModelRouteImport
      parentRoute: typeof BrandSlugRoute
    }
  }
}

interface BrandSlugRouteChildren {
  BrandSlugModelRoute: typeof BrandSlugModelRoute
}

const BrandSlugRouteChildren: BrandSlugRouteChildren = {
  BrandSlugModelRoute: BrandSlugModelRoute,
}

const BrandSlugRouteWithChildren = BrandSlugRoute._addFileChildren(
  BrandSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandSlugRoute: BrandSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
